### ISSUE TITLE
`Error: spawn npm ENOENT` when running on Windows 7 

### ISSUE THREAD

**Issue by biddster** [hapipal/hpal#16]
I'm not sure if windows is supported by hpal, but I'm seeing this:
```
C:\git>npx hpal new test-api

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
It was super slick on my mac, many thanks as this is such a time saver.

**Comment by devinivy** [comment]
I absolutely would like hpal to support Windows.  That said, I don't personally have access to a Windows machine and Travis CI doesn't seem to support it, which is a bit of an obstacle.

As for this particular issue, perhaps this points towards a solution: https://stackoverflow.com/questions/43230346/error-spawn-npm-enoent

**Comment by dpalmerjr** [comment]
It appears to be a related issue. In new.js for the internals.npmInit is the problem.  Instead of just calling npm in the ChildProcess.spawn you need to choose npm.cmd if it is windows.  Adding

// Node does not support PATHEXT on Windows
const npmCmd = process.platform === 'win32' ? 'npm.cmd' : 'npm';

and then changing the call to 

        const subproc = ChildProcess.spawn(npmCmd, ['init'], { cwd });

worked for me.

**Comment by devinivy** [comment]
Thanks a bunch for looking into it!  I would happily take a PR for this.  If we can't cover this code branch using travis CI, I think it's acceptable to [disable coverage](https://github.com/hapijs/lab#disable-code-coverage) for that line.
