### ISSUE TITLE
`hpal new`-generated package.json missing final newline

### ISSUE THREAD

**Issue by devinivy** [hapipal/hpal#29]
The package.json generated by `hpal new` does not have an ending newline, but npm adds a newline during `npm install`.  hpal should be consistent with this behavior of npm.

**Comment by franck-romano** [comment]
Hi @devinivy,

I would be happy to help !

I guess that the work should be done here between those lines: https://github.com/hapipal/hpal/blob/master/lib/commands/new.js#L50
and https://github.com/hapipal/hpal/blob/master/lib/commands/new.js#L59

Can you tell me if I'm wrong ? :)

Thanks !

**Comment by devinivy** [comment]
Awesome!  Yeah, the package.json file gets written twice: once to remove `name` and `version` prior to running `npm init`(https://github.com/hapipal/hpal/blob/master/lib/commands/new.js#L57) and once afterwards (https://github.com/hapipal/hpal/blob/master/lib/commands/new.js#L95).  It would probably be good to add the newline to the end of the file both times it's written.

**Comment by devinivy** [comment]
Resolved in #33.  Will release pretty soon!
