### ISSUE TITLE
"registerService" is not a method on the passed server

### ISSUE THREAD

**Issue by iljoo** [hapipal/hpal#34]
Not sure if it's a hpal issue, but certainly related to it or one of the hapipal family modules. The hpal generated project fails to register new Schmervice services with the following error:

```
AssertionError [ERR_ASSERTION]: "registerService" is not a method on the passed server.
    at new AssertionError (internal/assert.js:269:11)
```

Steps to reproduce:
1) Create a new hpal project (hpal new test_project && cd test_project && npm i)
2) Create a route and fill in the details (hpal new route root)
3) Install schmervice (npm i schmervice)
4) Create a new service (hpal new service simple)
5) Server now fails to start.

It used to work earlier, so my guess that it's some module change down the line that's causing trouble.

**Comment by iljoo** [comment]
Yep. Worked. Thanks a lot for the swift reply 👍

**Comment by sebastianhelbig** [comment]
@devinivy 
How to do this, now that schmervice is named "@hapipal/schmervice"?
Thanks a lot.

**Comment by devinivy** [comment]
@sebastianhelbig You can register the plugin onto the server yourself:
```js
await server.register('@hapipal/schmervice');
```

Or if you're using haute-couture and the pal boilerplate you can simply create a file named `lib/plugins/@hapipal.schmervice.js` exporting an empty object (i.e. no plugin configuration).  Here's an example: https://github.com/devinivy/hapipal-realworld-example-app/blob/main/lib/plugins/%40hapipal.schmervice.js.
