### ISSUE TITLE
Add avocat to docs

### ISSUE THREAD

**Issue by devinivy** [hapipal/hpal#44]
The [avocat](https://github.com/hapipal/avocat) module is missing from `hpal docs`.

**Comment by zemccartney** [comment]
@devinivy yo! I'm down to take care of this over the weekend if that'd be of help to ya. Whatever's good, just let me know 🙏

**Comment by devinivy** [comment]
That sounds cool to me— thanks! 🥂

**Comment by devinivy** [comment]
Resolved by #45
